#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    >&2 echo "Usage: $0 <name> <email>"
    >&2 echo "Feed commit hashes into stdin"
    exit 1
fi

AUTHOR="$1 <$2>"
AUTHOR_NAME="$1"
AUTHOR_EMAIL="$2"

let "count=0"
SED_SCRIPT=""
while read commit; do
    if [ "$commit" = "" ]; then
        break
    fi
    let "count+=1"
    COMMIT=$(git rev-parse --short $commit)
    SED_SCRIPT="$SED_SCRIPT -e 's/^pick $COMMIT/edit $COMMIT/'"
    SED_SCRIPT="$SED_SCRIPT -e '/^merge -C $COMMIT.*/a b'"
done </dev/stdin

if [ "$count" -eq "0" ]; then
    echo "stdin is empty"
    exit 1
fi

GIT_SEQUENCE_EDITOR="sed -i $SED_SCRIPT" git rebase -i --rebase-merges --root
for _ in $(seq 1 $count);
do
    GIT_COMMITTER_NAME="$AUTHOR_NAME" GIT_COMMITTER_EMAIL="$AUTHOR_EMAIL" git commit --amend --no-edit --author="$AUTHOR"
    git rebase --continue
done

echo "Author has been changed to \"$AUTHOR\" for $count commits"
